# http://www.ros.org/wiki/robot_mechanism_controllers/JointTrajectoryActionController
arm_controller:
 type: "robot_mechanism_controllers/JointTrajectoryActionController"
 joints:
   - shoulder_pan_joint
   - shoulder_pitch_joint
   - elbow_flex_joint
   - wrist_roll_joint
 gains:
   shoulder_pan_joint:
     p: 2400.0
     d: 18.0
     i: 800.0
     i_clamp: 4.0
   shoulder_pitch_joint:
     p: 1200.0
     d: 10.0
     i: 700.0
     i_clamp: 4.0
   elbow_flex_joint:
     p: 1000.0
     d: 6.0
     i: 600.0
     i_clamp: 4.0
   wrist_roll_joint:
     p: 700.0
     d: 4.0
     i: 450
     i_clamp: 4.0
    
 joint_trajectory_action_node:
  joints:
   - shoulder_pan_joint
   - shoulder_pitch_joint
   - elbow_flex_joint
   - wrist_roll_joint
  constraints:
   goal_time: 0.6
   r_shoulder_pan_joint:
    goal: 0.05
   shoulder_pitch_joint:
    goal: 0.05
   elbow_flex_joint:
    goal: 0.05
   wrist_roll_joint:
    goal: 0.05
