joint_limits:
  shoulder_pan_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.8
    has_acceleration_limits: true
    max_acceleration: 0.5
    angle_wraparound: false
  shoulder_pitch_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.8
    has_acceleration_limits: true
    max_acceleration: 0.5
    angle_wraparound: false
  elbow_flex_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.8
    has_acceleration_limits: true
    max_acceleration: 0.5
    angle_wraparound: false
  wrist_roll_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.8
    has_acceleration_limits: true
    max_acceleration: 0.5
    angle_wraparound: false
