# http://www.ros.org/wiki/navigation/Tutorials/Navigation%20Tuning%20Guide

controller_frequency: 5.0

TrajectoryPlannerROS:

  global_frame_id: /odom_combined
  publish_cost_grid_pc: true

  max_vel_x: 0.8
  min_vel_x: 0.2
  max_rotational_vel: 0.8
  min_in_place_rotational_vel: 0.2
  acc_lim_th: 0.1
  acc_lim_x: 0.1
  acc_lim_y: 0.1

  escape_vel: -0.2

  holonomic_robot: false
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
  goal_distance_bias: 0.6
  path_distance_bias: 0.8
  sim_time: 0.5
  sim_granularity: 0.025
  heading_lookahead: 0.325
  heading_scoring: true
  oscillation_reset_dist: 0.05

  vx_samples: 3
  vtheta_samples: 10
  dwa: false

