#START VOXEL STUFF
#map_type: voxel
#origin_z: 0.0
#z_resolution: 0.2
#z_voxels: 1 # 0.3*4 = 1.2 m
#unknown_threshold: 9
#mark_threshold: 0
#END VOXEL STUFF
map_type: costmap

transform_tolerance: 0.5
obstacle_range: 2.5
#max_obstacle_height: 2.0
raytrace_range: 3.0

footprint: [[0.35, -0.20], [0.35, -0.05], [0.45, -0.05], [0.45, 0.05], [0.35, 0.05], [0.35, 0.20],[-0.20, 0.20], [-0.20, -0.20]]
footprint_padding: 0.01
inflation_radius: 0.15

inscribed_radius: 0.2
circumscribed_radius: 0.2
cost_scaling_factor: 10.0
lethal_cost_threshold: 100

track_unknown_space: true
unknown_cost_value: 255

# http://www.ros.org/wiki/costmap_2d
# observation_sources: scan kinect
observation_sources: scan scan_fake

scan: {data_type: LaserScan, topic: /scan,
  observation_persistence: 10.0, marking: true, clearing: true, obstacle_range: 2.5}

scan_fake: {data_type: LaserScan, topic: /scan_fake, observation_persistance: 10.0, marking: true, clearing: true, obstacle_range: 2.5}

# consider downsampling kinect pointcloud
#kinect: {sensor_frame: /camera_rgb_optical_frame, data_type: PointCloud2, topic: /cam3d/depth/points_throttled, expected_update_rate: 0.5,
#  observation_persistence: 10.0, marking: true, clearing: true, max_obstacle_height: 1.3, min_obstacle_height: 0.2, obstacle_range: 5.0}

#robot_radius: 0.30 # this is used if footprint is not specified

